site_name: Documentation
site_author: Cortexflow Team
site_url: https://docs.cortexflow.org
site_description: >-
  Offical CortexFlow documentation

repo_name: "CortexBrain"
repo_url: "https://github.com/CortexFlow/CortexBrain"

theme:
  language: en
  name: material
  icon: 
    repo: fontawesome/brands/github
  font: 
    text: Lato
  logo : ./assets/logo512.png
  favicon: ./assets/logo512.png
  palette:
    - scheme: default
      primary: "#7D88EC"  #light mode
      accent: "#FF5733"  
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
    - scheme: slate
      primary: "#030712"  # Dark mode
      accent: "#030712"
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
  
  markdown_extensions:
    - toc:
        permalink: true


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - content.tabs.link



extra_css:
  - stylesheets/style.css
extra:
  generator: false
  copyright: "Copyright &copy; 2025 CortexFlow"
  social: #footer
    - icon: fontawesome/brands/github
      link: https://github.com/CortexFlow/CortexBrain
    - icon: fontawesome/brands/dev
      link: https://dev.to/cortexflow
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - tags:
  - search:
  - rss:
        match_path: test-report/reports/.*
        date_from_meta:
          as_creation: date

nav:
  - Home: index.md
  - Getting Started: getting-started/installation.md
  - CLI: 
    - cfcli/overview.md
    - cfcli/quick-start-guide.md
    - cfcli/Agent-API-Overview.md
    
  - Test Report: 
    - test-report/test-report.md
    - Reports:
      - test-report/reports/March2025/March2025.md  

  - Contact: contacts/contact.md
  
