[package]
name = "identity"
version = "0.1.0"
edition = "2024"

[dependencies]
aya = "0.13.1"
aya-log = "0.2.1"
bytes = "1.4"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
libc = "0.2.172"
bytemuck = {version ="1.23.0",features = ["derive"]}
bytemuck_derive = "1.10.1"
cortexbrain-common = { path = "../../../common" }

nix = { version = "0.30.1", features = ["net"] }
